#ifndef CONFIG_H
#define CONFIG_H

// --- Definições de Pinos ---
#define SENSOR_POWER_CTRL_PIN GPIO_NUM_13 // GPIO para controlar o MOSFET dos sensores

#define MODEM_PWRKEY_PIN   GPIO_NUM_4  // GPIO para ligar/desligar o modem 
#define MODEM_RST_PIN      GPIO_NUM_5  // GPIO para resetar o modem
#define MODEM_TX_PIN       GPIO_NUM_27 // GPIO TX do ESP32 para RX do Modem
#define MODEM_RX_PIN       GPIO_NUM_26 // GPIO RX do ESP32 para TX do Modem

#define DSM501A_PM25_PIN GPIO_NUM_19
#define DSM501A_PM10_PIN GPIO_NUM_18


// --- Configurações de Tempo e Delays ---
#define SENSOR_STABILIZATION_DELAY_MS 60 
#define TIME_TO_SLEEP_INTERVAL_MINUTES 1   

// --- Configurações GSM/GPRS ---
const char APN[] = "zap.vivo.com.br"; 
const char GPRS_USER[] = "vivo";      
const char GPRS_PASS[] = "vivo";      

// --- Configurações AWS IoT Core ---
#define AWS_IOT_ENDPOINT "a33tdbpdq467x1-ats.iot.us-east-2.amazonaws.com"
#define AWS_IOT_CLIENT_ID "LilyGo" 
#define AWS_IOT_PUBLISH_TOPIC "telemetria/lilygo/LilyGo" 


bool comm_manager_sync_time(int timezone_offset_hours = -3);

// --- Certificados AWS  ---
const char AWS_CERT_CRT[] = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUdSVUKOyup2Y2VVQfF894cyqvWb0wDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTI1MDYwMTAyMDU0
NFoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMguu9vTR38FeIvXKrdi
fqrWZ8NO08TX7NrQEo37YDrOsG8RRaE8IEVjRMHn8OJf0gsFrCU/L4gIkBIOCgi3
gTUydMgId0NkzzuMJcmmfNVgpqJcoaThCLOAbmbGcVQ7noPc2m7BY56lZykNHq0K
Z+1lwer0p4xBGIhfYMy+gQSQvEMv+Jz/kPgX6rwUsFEoehc9LEgr3LQ64uRnTk4h
JO3eGkTR245+nEkq/oO6zNWYI+itLOoGRTDwIciCQ4s7Cx37lqMHvwkJK8KzKvaK
5c9fTqxciCpH4MV/ysUF+UIkN9iulauh8UzwJoTagu+jQJSVZgLUkml7ndgLZYPM
3icCAwEAAaNgMF4wHwYDVR0jBBgwFoAUKPOE9Z+JcFBzPQKssCIw5HeEJQMwHQYD
VR0OBBYEFBpEIttdk3s2A0D/9LEeb/QT7jgyMAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAndUWcJN5K1Yyc8nBO0vlwQ2kO
3WEX9UjmVHHDCrDJK3kK/VvFPkjkBKe44KEP1uwezz0y5R0CWGQdVdxGqlc5v8A7
FAT0jnqXLoecVKei1XJb/jZUAmjts+dkWXNw2o48tjiv8r/t8fRwDLVNp3yGib9R
dkxGNmzFCgfBFA0iR/iWudOxO+54Qo0M90EQ/rAyFdjsJU/3kwICTTFsX4JI8AwA
TYkoD4YMzTwcdx89YxzpeY1+NcbjimIKUhmRMrq5fOZoqLF0c4ilWbyzcHXTiFtS
/r91XqMyzfHVcqBeGZiNlOpJFeAIzHRIewHjWrRZrbjCvuT5B01QTQOsZnbs
-----END CERTIFICATE-----
)EOF";

const char AWS_PRIVATE_KEY[] = R"EOF(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAyC6729NHfwV4i9cqt2J+qtZnw07TxNfs2tASjftgOs6wbxFF
oTwgRWNEwefw4l/SCwWsJT8viAiQEg4KCLeBNTJ0yAh3Q2TPO4wlyaZ81WCmolyh
pOEIs4BuZsZxVDueg9zabsFjnqVnKQ0erQpn7WXB6vSnjEEYiF9gzL6BBJC8Qy/4
nP+Q+BfqvBSwUSh6Fz0sSCvctDri5GdOTiEk7d4aRNHbjn6cSSr+g7rM1Zgj6K0s
6gZFMPAhyIJDizsLHfuWowe/CQkrwrMq9orlz19OrFyIKkfgxX/KxQX5QiQ32K6V
q6HxTPAmhNqC76NAlJVmAtSSaXud2Atlg8zeJwIDAQABAoIBAQCeD6CPgzTJy+UR
7dQxtpizhdWqdjxqCeBgKbjs2NZzuK3BFQ84r0P/5dDtlpkx9VzhDRqO0mRScghn
6SPtHA/ulCd3po+c7CVhLFjN7yJUTRtlyeRsTq9TJI6Hohrr2qNgFOt4VkS1iH57
AHv/P98tqJJEVedRrDiVvVGueKFgmw3qAVS90JF0bhool7wx2vDMkpT+HVDCx7yA
ifoiv9xKd25NdXGBPmBvZbSFw8tvAr27lz/7h9TOl+wvsQVr7eBbivJQTstqXYQI
MM79Shcb+Qz69Pl+f19nnyqvLGqzWPVygwMr8PTwQJaEFrPZbPq/OTU35uRmjmVf
NOE8pgHZAoGBAOw+1kbWnMDYZBKShlK8b6c+b9E+Iw6tUxHBEMSGbldcYyDYzact
7HQmF6xVXgieekadH3V9B9pRCJGnCJWi6iq3vrnsQ/iy6N8NL9sxWeF2sme6iP1V
UvJqp3/J4dQFnbOP9zH7utluNtnWPPGX8rMRKlAT8MbCaUCdrewWczMLAoGBANjr
646vIgOQdINXDjh9QIVHLRM+JWelMmnf+GpXoXkTCF1qCfBC8q/l0behQh7CSfbt
+nd/88O89ZCEv6k+GRTK4szRRqXfWbgeNIrQYauRzJ+bU2EZsClJCYuQeGajjS02
QZv7HlVr34rJBHBjktRYeOuwXgNmWWaOKeIe+fLVAoGAV49Kl+K/InKRVJjeFBgn
QdNQWjsvfycaXMAz2MMCbnqdevUf89B/jOT5bTQOsB8crsNZf5AhsvbJuEIyWlOR
etezZvF8l9annNQkYpc9+uSlZvCqCUrwfUyuXByVCKI0OvMm6W2laSUCS2auG9T3
bQr1pcxeNyyjGgHXDmObutUCgYAaQeyAmAh4//pqj5YkFl1CBMybALHMav3APSE3
1iWwnzIrBJPxZlk0G5CYNsfnK0OCxWnFH1LlhbD/7mG43dBxaOGtQ0PW/kNA+z8G
8pRwDTUEuOuN3GsrhDDImRNJ8VA8gc3NUMdqNaWYih6kcBks5Qy2EuI+bRwzQtAl
E/TThQKBgDiM/ko4CO4vn8Hcpn18/nqzkY5UWacvdgq6I9RatqnRLmQH/bugEX5x
X7yf/2u6qCmqdN3nDSjzTcEh+UnOjU4e9iqctWrS+dYTWEFGtLfHxGyH6n4qntUL
t89YDX0n9zzxA5VBNMr91SaewaMQcRaufpr3KhPMA1yPl2zOblay
-----END RSA PRIVATE KEY-----
)EOF";

const char AWS_IOT_ROOT_CA[] = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";


#endif // CONFIG_H